import { jsPDF } from 'jspdf'
import type { KMapModel } from '../../../core/kmap'
import { kmapToTruthTable } from '../../../core/kmap/truth-table'
import { minterms, maxterms, dontCares } from '../../../core/kmap'

interface PdfExportData {
  kmap: KMapModel
  simplifiedExpression: string
  originalExpression: string
  showSOP: boolean
  sopTerms: readonly string[]
  posTerms: readonly string[]
  groupCount: number
}

function drawKMapGrid(doc: jsPDF, kmap: KMapModel, startX: number, startY: number, cellSize: number) {
  const { layout, cells } = kmap
  const labelWidth = 12
  const headerHeight = 10

  doc.setFontSize(7)
  doc.setTextColor(100, 100, 100)

  for (let c = 0; c < layout.cols; c++) {
    const x = startX + labelWidth + c * cellSize + cellSize / 2
    doc.text(layout.colLabels[c]!, x, startY + 4, { align: 'center' })
  }

  for (let r = 0; r < layout.rows; r++) {
    const y = startY + headerHeight + r * cellSize + cellSize / 2 + 1
    doc.text(layout.rowLabels[r]!, startX + labelWidth - 2, y, { align: 'right' })
  }

  doc.setFontSize(6)
  doc.setTextColor(139, 92, 246)
  const colVarStr = layout.colVariables.join('')
  doc.text(colVarStr, startX + labelWidth + (layout.cols * cellSize) / 2, startY + 1, { align: 'center' })

  const rowVarStr = layout.rowVariables.join('')
  const rowVarY = startY + headerHeight + (layout.rows * cellSize) / 2
  doc.text(rowVarStr, startX + 3, rowVarY, { align: 'center' })

  for (let r = 0; r < layout.rows; r++) {
    for (let c = 0; c < layout.cols; c++) {
      const cell = cells[r]![c]!
      const x = startX + labelWidth + c * cellSize
      const y = startY + headerHeight + r * cellSize

      doc.setDrawColor(200, 200, 200)
      doc.setFillColor(30, 41, 59)
      doc.rect(x, y, cellSize, cellSize, 'FD')

      const val = cell.value
      let text = ''
      let r2 = 0, g = 0, b = 0
      if (val === 1) { text = '1'; r2 = 74; g = 222; b = 128 }
      else if (val === 0) { text = '0'; r2 = 148; g = 163; b = 184 }
      else if (val === 'X') { text = 'X'; r2 = 250; g = 204; b = 21 }
      else { text = `m${cell.minterm}`; r2 = 100; g = 116; b = 139 }

      doc.setFontSize(9)
      doc.setTextColor(r2, g, b)
      doc.text(text, x + cellSize / 2, y + cellSize / 2 + 1.5, { align: 'center' })

      doc.setFontSize(5)
      doc.setTextColor(100, 116, 139)
      doc.text(String(cell.minterm), x + cellSize - 1, y + cellSize - 1, { align: 'right' })
    }
  }
}

function drawTruthTable(doc: jsPDF, kmap: KMapModel, startX: number, startY: number) {
  const variables = kmap.layout.variables
  const n = variables.length
  const tt = kmapToTruthTable(kmap)

  doc.setFontSize(8)
  doc.setTextColor(139, 92, 246)
  doc.text('Truth Table', startX, startY)

  const colWidths = Array(n).fill(8)
  colWidths.push(8)
  colWidths.push(10)
  const totalWidth = colWidths.reduce((a, b) => a + b, 0)

  let y = startY + 5
  doc.setFillColor(30, 41, 59)
  doc.rect(startX, y, totalWidth, 5, 'F')

  doc.setFontSize(5)
  doc.setTextColor(241, 245, 249)
  let x = startX
  for (const v of variables) {
    doc.text(v, x + colWidths[variables.indexOf(v)]! / 2, y + 3.5, { align: 'center' })
    x += colWidths[variables.indexOf(v)]!
  }
  doc.text('F', x + 4, y + 3.5, { align: 'center' })
  doc.text('#', x + 12, y + 3.5, { align: 'center' })

  y += 5
  for (let minterm = 0; minterm < 2 ** n; minterm++) {
    const bits = minterm.toString(2).padStart(n, '0')
    const value = tt.outputs[minterm]

    if (value === 1) {
      doc.setFillColor(22, 163, 74, 0.15)
      doc.rect(startX, y, totalWidth, 4, 'F')
    }

    x = startX
    doc.setFontSize(5)
    doc.setTextColor(241, 245, 249)
    for (let i = 0; i < n; i++) {
      doc.text(bits[i]!, x + colWidths[i]! / 2, y + 3, { align: 'center' })
      x += colWidths[i]!
    }

    let r2 = 148, g = 163, b = 184
    if (value === 1) { r2 = 74; g = 222; b = 128 }
    else if (value === 0) { r2 = 148; g = 163; b = 184 }
    else if (value === 'X') { r2 = 250; g = 204; b = 21 }
    doc.setTextColor(r2, g, b)
    doc.text(value === null ? '-' : String(value), x + 4, y + 3, { align: 'center' })

    doc.setTextColor(100, 116, 139)
    doc.text(`m${minterm}`, x + 12, y + 3, { align: 'center' })

    y += 4
  }
}

export function exportKMapToPdf(data: PdfExportData) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(139, 92, 246)
  doc.text('K-Map Simplification Report', pageWidth / 2, 20, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated by DigiWorld - Digital Logic Concept Lab`, pageWidth / 2, 26, { align: 'center' })
  doc.text(`Mode: ${data.showSOP ? 'Sum of Products (SOP)' : 'Product of Sums (POS)'}`, pageWidth / 2, 31, { align: 'center' })

  doc.setDrawColor(139, 92, 246)
  doc.setLineWidth(0.3)
  doc.line(margin, 35, pageWidth - margin, 35)

  doc.setFontSize(10)
  doc.setTextColor(139, 92, 246)
  doc.setFont('helvetica', 'bold')
  doc.text('K-Map Grid', margin, 42)

  const maxCellSize = 10
  const gridHeight = data.kmap.layout.rows * maxCellSize
  const gridX = margin
  const gridY = 46

  drawKMapGrid(doc, data.kmap, gridX, gridY, maxCellSize)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(139, 92, 246)
  doc.text('Simplified Expression', margin, gridY + gridHeight + 22)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(241, 245, 249)
  doc.text(`Original: ${data.originalExpression}`, margin, gridY + gridHeight + 28)
  doc.text(`Simplified: ${data.simplifiedExpression}`, margin, gridY + gridHeight + 34)

  const activeTerms = data.showSOP ? data.sopTerms : data.posTerms
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text(`Terms (${activeTerms.length}): ${activeTerms.join(' + ')}`, margin, gridY + gridHeight + 40)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(139, 92, 246)
  doc.text('Group Analysis', margin, gridY + gridHeight + 50)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(241, 245, 249)
  doc.text(`Number of groups: ${data.groupCount}`, margin, gridY + gridHeight + 56)
  doc.text(`Variables: ${data.kmap.layout.variables.join(', ')}`, margin, gridY + gridHeight + 62)

  const ones = minterms(data.kmap)
  const zeros = maxterms(data.kmap)
  const dc = dontCares(data.kmap)
  doc.text(`Minterms (1s): ${ones.length > 0 ? ones.join(', ') : 'none'}`, margin, gridY + gridHeight + 68)
  doc.text(`Maxterms (0s): ${zeros.length > 0 ? zeros.join(', ') : 'none'}`, margin, gridY + gridHeight + 74)
  if (dc.length > 0) {
    doc.text(`Don't-cares (X): ${dc.join(', ')}`, margin, gridY + gridHeight + 80)
  }

  const ttStartY = gridY + gridHeight + (dc.length > 0 ? 92 : 86)
  if (ttStartY + 80 < doc.internal.pageSize.getHeight() - 20) {
    drawTruthTable(doc, data.kmap, margin, ttStartY)
  } else {
    doc.addPage()
    drawTruthTable(doc, data.kmap, margin, 20)
  }

  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(7)
  doc.setTextColor(100, 116, 139)
  doc.text('DigiWorld - Digital Logic Concept Lab | chalkandduster.com', pageWidth / 2, footerY, { align: 'center' })

  doc.save('kmap-simplification-report.pdf')
}
